apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

resources:
  - ../../base

generators:
- configmap-dashboards.yaml